import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/context/Providers";
import { BackgroundWrapper } from "@/components/ui/background-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body
        className={`
          text-foreground
          antialiased
        `}
      >
        <div className="liquid-orb-bg" />
        <BackgroundWrapper>
          <Providers>{children}</Providers>
        </BackgroundWrapper>
      </body>
    </html> 
  );
}
